### ISSUE TITLE
What could be possible for injection failing ? 

### ISSUE THREAD

**Issue by SagiSatish** [ICSec/airpwn-ng#14] opened 2016-07-16 08:23 UTC
I tried injecting on an open network but it never worked. 
My configuration is like this:
wlan1(TP-Link TL-WN722N ) - monitor mode 
wlan0 - injecting interface 
MotoG3  Firefox 47.0 Android Browser - Client

```
$ python airpwn-ng -m wlan1 -i wlan0 --inject example-injects/wargames
[!] It appears your are trying to attack a WEP/WPA protected network. Please ensure -m is your dot11 tap interface and that -i is connected to the target AP.
[+] Loaded injection file example-injects/wargames
[!] You are starting your attack in broadcast mode. This means you will inject packets into all clients you are able to detect. Use with caution.
```
It didn't produce any output after that. I browsed many HTTP websites, but never got any injected response.  In Wireshark also I am unable to find any injected packets. 

I tried on a wpa2  encrypted too.  Started dot11decrypt and successfully captured the handshake and started the airpwn-ng with tap0 interface created by dot11decrypt. 

```
$ dot11decrypt wlan1 wpa:My-Net:MyPassword
Using device: tap0
Device is up.
AP found: My-Net: bd:60:31:38:7a:4e
Captured handshake for My-Net (bd:60:31:38:7a:4e): cd:89:51:78:7a:5d
```
```
$ ./airpwn-ng -m tap0 -i wlan0 --inject example-injects/wargames
WARNING: No route found for IPv6 destination :: (no default route?)

airpwn-ng - the new and improved 802.11 packet injector

[!] It appears your are trying to attack a WEP/WPA protected network. Please ensure -m is your dot11 tap interface and that -i is connected to the target AP.
[+] Loaded injection file example-injects/wargames
[!] You are starting your attack in broadcast mode. This means you will inject packets into all clients you are able to detect. Use with caution.
[*] Injecting Packet to victim cd:89:51:78:7a:5d (TOTAL: 1 injected packets)
```

At this time I am able to find that packets are getting injected. I even verified that using Wireshark but my browser never shows any injected response.  

Can anybody help me on this ?

**Comment by Jack64** [comment] 2016-07-16 08:37
Hey @SagiSatish . Indeed I think I may know what the problem is.

There's this extremely naive assumption that if you're injecting on an open network, you'll be feeding your monitor mode NIC to the -i flag. I also assumed you'd be using airmon-ng and thus the resulting interface would be monN or wlanNmon.
Hence, this line of code (@ https://github.com/ICSec/airpwn-ng/blob/master/lib/airpwn_ng.py#L340) makes the distinction between building an 802.11 packet (for use with open networks mode) or a standard Ethernet packet which will be routed by the AP (for use with WPA network mode).

This explains your issue with open networks, given your interface names. (and will be fixed soon, probably via a flag you set for encrypted mode or open network mode).

Now about the WPA issue, are you connected to the target WLAN with wlan0 when you're trying to inject? It says injecting packet so that means dot11 is working properly and airpwn-ng can see the GET requests on tap0 and triggers the injection to be sent.
You should check the target device to see if the injected packet is arriving, and when it is arriving. This will let you know if you're winning the race condition or not.
There are other reasons why it may not work, one of them is IPv6 which is currently not supported.

**Comment by SagiSatish** [comment] 2016-07-16 09:36
Thanks for quick reply. 

I did the following commands to make my wlan1 interface in monitor mode instead of using airmon-ng or creating a separate monitor mode with iw command. 
I am sure that wlan1 is in monitor mode. 
```
ifconfig wlan1 down
iwconfig wlan1 mode monitor
ifconfig wlan1 up
iwconfig wlan1
``` 
I also tried giving the same monitor mode interface to both -i and -m flag, but it didn't work. I will try giving making the name to something like "wlan1mon" and will post the result. 

Coming to WPA issue, Yes wlan0 is connected to Access point specified and I can verify that airpwn-ng injecting some packets by seeing at airpwn-ng output and Wireshark. But in the target device, I can only see the legitimate web page. There is no injected page response at target device.

```
[!] No cookie on client 192.168.11.57  for website www.google.co.in
[*] Injecting Packet to victim cd:89:51:78:7a:5d (TOTAL: 6 injected packets)
```

**Comment by SagiSatish** [comment] 2016-07-16 10:01
Just created a wlan1mon interface and tried to inject. airpwn-ng didn't produce any output and  In Wireshark also I am unable to see any injected packets. 

```
$ iw dev wlan1 interface add wlan1mon type monitor
$ airodump-ng wlan1mon
```


```
./airpwn-ng -m wlan1mon -i wlan1mon --inject example-injects/wargames
WARNING: No route found for IPv6 destination :: (no default route?)

airpwn-ng - the new and improved 802.11 packet injector

[+] Loaded injection file example-injects/wargames
[!] You are starting your attack in broadcast mode. This means you will inject packets into all clients you are able to detect. Use with caution.
```

**Comment by Jack64** [comment] 2016-07-16 11:09
You should debug with a computer as the target first, just to make sure the race condition is being  won and the target is getting the packet. I have that WiFi card and it's not particularly fast so your results may vary.

**Comment by stryngs** [comment] 2016-07-16 12:54
Hmm, I rock that TP link as the card I test airpwn-ng with.  I've never had an issue with it; however, it doesn't mean there aren't any.  I would recommend going to sites like risky.biz or foo.com for testing.  In the fork I work on, I've noticed there are instances of some sites (stackoverflow) not being affected by airpwn-ng.

As far as your issue goes; let's do this:
1 - Ensure you're using aircrack-ng from the svn or at a minimum:  http://download.aircrack-ng.org/aircrack-ng-1.2-rc4.tar.gz  -- The repo is never up to date.

2 - airmon-ng start <desired NIC>

3 - aireplay-ng -9 <newly named interface that took NIC above and made it most likely wlanXmon>

4 - If it says injection is working, you should be good to go.

5 - Ensure both victim and attacker machine are at least 10 ft away from the router, and a minimum of 5 ft from each other (10 is more preferable...)

6 - ./airpwn-ng --injection -m <wlanXmon> -i <wlanxmon>

7 - On the victim machine, proceed over to foo.com

8 - Report back what happens =)

**Comment by SagiSatish** [comment] 2016-07-16 20:19
@Jack64  Thanks for pointing me on race condition. I am also found that legitimate packets reached before the injected packets. 

@stryngs Thanks for the write-up.  I followed all your steps. My injection test working fine. I maintained proper distance. I succeeded at the rate of 1/35 attempts.  I tried browsing the websites given by you and many other random names(which probably may not exist).  I found some of the problems after analyzing more than an hour at the Wireshark captures. 

1)  For the first time when I browse a site which is mamam.com from internet explorer on windows 10, I succeeded.  Then I cleared my cache(to make sure the cache not served) and all other data. Then tries to browse the mamam.com surprisingly packets not injected. After that I tried with different browsers, private/incognito mode, but packets never injected at all. I even didn't get any output from airpwn-ng regarding the revisit of the site.  When I tried the same on  Linux machine with firefox, it never worked. 
2) Race condition is won by legitimate packets. It seems to be this WIFI card is not fast enough.

For the WPA setup, It never worked. I am sure that dot11decrypt works fine and created tap0 interface. When I ran airpwn-ng, I got output saying packets injected but I never received them at the target device( Analyzed through Wireshark).

**Comment by Jack64** [comment] 2016-07-22 22:00
@SagiSatish If the real packets are arriving before the injected ones then you're not winning the race condition and that's why the attack is not working. 

I've made airpwn-ng work on a OnePlus One phone that had Kali installed paired with that same TP-Link TL-WN722N over OTG and it worked after a few tries (not 1/35, more like 1/5) so I'm not really sure what's slowing you down.

**Comment by stryngs** [comment] 2016-08-02 03:41
@SagiSatish Have we successfully answered your concerns?

**Comment by SagiSatish** [comment] 2016-08-02 11:44
@Jack64 I don't find any bottleneck on resources usage, it may be because of my WiFi card.

@stryngs Yes, thanks fo the help. It's all about race condition and speed of the WiFI adapter.

**Comment by stryngs** [comment] 2016-08-02 12:55
Closing this issue out.

**Closed by stryngs** 2016-08-02 12:55 UTC
